# cloudbuild.yaml for React app using Docker
substitutions:
  _SERVICE_NAME: "auth"
  _REGION: "europe-west1"
  _IMAGE: "gcr.io/cloudrun/placeholder@sha256:aafee0b13cdc19d6dd055be74d3405b9435b8108b0a3f181c01c38b4c8abf899"

steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloudrun/placeholder"
    id: "Build Docker image"
    args: ["build", "-t", "$_IMAGE:$SHORT_SHA", "."]

  # Step 2: Push to Google Container Registry
  - name: "gcr.io/cloudrun/placeholder"
    id: "Push Docker image"
    args: ["push", "$_IMAGE:$SHORT_SHA"]

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/cloudrun/placeholder"
    id: "Deploy to Cloud Run"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image"
      - "$_IMAGE:$SHORT_SHA"
      - "--region"
      - "$_REGION"
      - "--platform=managed"
      - "--allow-unauthenticated"

images:
  - "$_IMAGE:$SHORT_SHA"

timeout: "900s"
